import {pathfind} from './terrain.js';
import {coverageRoute,dispatch,emit,platformDeviceCode,task,uid} from './simulation.js';

export const PLATFORM_URL=import.meta.env.VITE_PLATFORM_URL||'http://localhost:8080/api';
const KEY=import.meta.env.VITE_SIMULATION_KEY||'local-sim-2026';
const headers={'Content-Type':'application/json','X-Simulation-Key':KEY};
const ANCHOR_LNG=116.4,ANCHOR_LAT=39.91,M_PER_DEG=111320,LNG_METERS=M_PER_DEG*Math.cos(ANCHOR_LAT*Math.PI/180);

export const geoToLocal=position=>({x:(+position.longitude-ANCHOR_LNG)*LNG_METERS,z:(+position.latitude-ANCHOR_LAT)*M_PER_DEG});

export async function sendMessage(message){const response=await fetch(`${PLATFORM_URL}/integration/v1/messages`,{method:'POST',headers,body:JSON.stringify(message)});if(!response.ok)throw Error(`平台返回 HTTP ${response.status}`);const body=await response.json();if(body.code!==200)throw Error(body.message||'平台拒绝消息');return body.data;}

export async function takeCommands(deviceCode){const response=await fetch(`${PLATFORM_URL}/integration/v1/devices/${encodeURIComponent(deviceCode)}/commands`,{headers:{'X-Simulation-Key':KEY}});if(!response.ok)throw Error(`指令通道 HTTP ${response.status}`);const body=await response.json();if(body.code!==200)throw Error(body.message||'指令通道失败');return body.data||[];}

export function registrationEnvelope(state,device){return {schemaVersion:'1.0',messageId:uid(),sessionId:state.sessionId,type:'device.register',timestamp:new Date().toISOString(),source:'simulator',deviceId:device.id,sequence:0,simulationTimeSeconds:state.time,payload:{deviceCode:platformDeviceCode(device),name:device.name,deviceType:device.type,battery:device.battery,position:{x:device.x,y:device.y,z:device.z},cruise:device.cruise,maxDistance:device.maxDistance}};}

export function telemetryEnvelope(state,device,sequence){return {schemaVersion:'1.0',messageId:uid(),sessionId:state.sessionId,type:'device.telemetry',timestamp:new Date().toISOString(),source:'simulator',deviceId:device.id,sequence,simulationTimeSeconds:state.time,payload:{deviceCode:platformDeviceCode(device),battery:Math.round(device.battery),state:device.state,position:{x:device.x,y:device.y,z:device.z}}};}

export function applyCommand(state,command){const p=command.payload||{},commandId=p.commandId||command.messageId,n0=structuredClone(state);n0.processedCommands??=[];if(n0.processedCommands.includes(commandId))return {state:n0,duplicate:true};const device=n0.devices.find(d=>platformDeviceCode(d)===p.deviceCode)||n0.devices.find(d=>d.id===command.deviceId);if(!device)return {error:'找不到指令对应设备'};const reject=reason=>{n0.processedCommands=[commandId,...n0.processedCommands].slice(0,200);emit(n0,'task.ack',device.id,{commandId:p.commandId,taskId:p.taskId,taskCode:p.taskCode,accepted:false,reason});return {state:n0,error:reason};};if(p.action==='CANCEL'){const localTask=n0.tasks.find(t=>t.platformTaskCode===p.taskCode);if(localTask){localTask.status='已取消';localTask.stage='已取消';emit(n0,'task.result',localTask.deviceId,{taskId:p.taskId,taskCode:p.taskCode,outcome:'CANCELLED'});}n0.processedCommands=[commandId,...n0.processedCommands].slice(0,200);return {state:n0};}if(p.action==='RETURN_HOME')return reject('UNSUPPORTED_COMMAND');let n=n0;if(p.action==='SEARCH'){if(device.type!=='uav')return reject('CAPABILITY_MISMATCH');const route=p.target?.longitude===undefined?coverageRoute(0,1):[{x:geoToLocal(p.target).x,z:geoToLocal(p.target).z}];task(n,device,'空中侦察',route,null,{taskId:p.taskId,taskCode:p.taskCode,commandId:p.commandId});n.processedCommands=[commandId,...n.processedCommands].slice(0,200);return {state:n};}if(device.type!=='dog')return reject('CAPABILITY_MISMATCH');const position=geoToLocal(p.target||{}),eventId=String(p.targetCode||p.eventId||uid()).replace(/^SIM-/,''),event=n.events.find(e=>e.id===eventId);if(!event){n.events.push({id:eventId,platformTargetCode:p.targetCode,kind:'person',x:position.x,z:position.z,severity:'高',status:'待复核',created:n.time});}const result=dispatch(n,eventId,device.id);if(result.error)return reject(result.error);n=result.state;n.processedCommands=[commandId,...n.processedCommands].slice(0,200);const localTask=n.tasks[0];localTask.platformTaskId=p.taskId;localTask.platformTaskCode=p.taskCode;localTask.commandId=p.commandId;localTask.id=String(p.taskId||localTask.id);const ack=n.messages.find(m=>m.type==='task.ack'&&m.deviceId===device.id);if(ack){ack.correlationId=p.taskCode;ack.payload={...ack.payload,commandId:p.commandId,taskId:p.taskId,taskCode:p.taskCode,accepted:true};}return {state:n};}
