import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import World from './World.jsx';
import {TYPES,uid,fresh,region,addEvent,randomEvent,dispatch,step,log,cancelTask,startDevices,returnDevices,createDevice,normalizeBerths,emit,DOG_MAX_DISTANCE} from './simulation.js';
import {BASE,WORLD,surfaceHeight} from './terrain.js';
import './app.css';
import './guide.css';
import './follow.css';
const STORAGE='sky-v4';
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE));if(s?.version===4&&['devices','events','tasks','logs'].every(k=>Array.isArray(s[k])))return normalizeBerths(s);}catch{}return fresh();}
function App(){
 const [s,set]=useState(load),[run,setRun]=useState(false),[speed,setSpeed]=useState(1),[placing,setPlacing]=useState(false),[kind,setKind]=useState('person'),[severity,setSeverity]=useState('高'),[selected,select]=useState(null),[tab,setTab]=useState('events'),[modal,setModal]=useState(null),[toast,notify]=useState(''),[camera,setCamera]=useState({mode:'home',seq:0}),[filter,setFilter]=useState(''),[freeHud,setFreeHud]=useState(false),[left,setLeft]=useState(true),[right,setRight]=useState(false),[journal,setJournal]=useState(false),[pilot,setPilot]=useState(''),[flySpeed,setFlySpeed]=useState(30),[saveError,setSaveError]=useState(false);
 const stateRef=useRef(s);stateRef.current=s;window.__sim=s;const visibleEvents=s.events.filter(e=>!e.archived),prevTasks=useRef(new Set(s.tasks.filter(t=>t.status==='已完成').map(t=>t.id)));
 useEffect(()=>{if(!run)return;const id=setInterval(()=>set(v=>step(v,.2*speed)),200);return()=>clearInterval(id);},[run,speed]);
 useEffect(()=>{const save=()=>{try{localStorage.setItem(STORAGE,JSON.stringify(stateRef.current));setSaveError(false);}catch{setSaveError(true);}};const id=setInterval(save,1500);window.addEventListener('beforeunload',save);return()=>{clearInterval(id);save();window.removeEventListener('beforeunload',save);};},[]);
 useEffect(()=>{for(const t of s.tasks.filter(t=>t.status==='已完成'))if(!prevTasks.current.has(t.id)){prevTasks.current.add(t.id);notify(`${t.deviceName} · ${t.phase==='返回基地'?'已返回集结中心':t.phase==='地面复核'?'现场处理完成，设备原地待命':'空中侦察完成，等待地面复核'}`);}},[s.tasks]);
 useEffect(()=>{const now=Date.now(),timers=s.events.filter(e=>e.status==='已处理'&&!e.archived).map(e=>setTimeout(()=>set(v=>{const n=structuredClone(v),target=n.events.find(x=>x.id===e.id);if(target&&!target.archived){target.archived=true;log(n,'已处理灾情从当前态势中移除，历史记录保留');}return n;}),Math.max(0,8000-(now-(e.processedWallTime||now)))));return()=>timers.forEach(clearTimeout);},[s.events]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>notify(''),6500);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{const fn=e=>{if(e.key==='Escape'){setPlacing(false);setModal(null);}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[]);
 const view=(mode,extra={})=>setCamera({mode,...extra,seq:performance.now()});
 const focus=(x,z,y)=>view('focus',{x,z,y});
 const follow=id=>{view('follow',{deviceId:id});setLeft(false);};
 const mutate=fn=>set(v=>{const n=structuredClone(v);fn(n);return n;});
 const event=visibleEvents.find(e=>e.id===selected),active=s.tasks.filter(t=>t.status==='执行中'),following=camera.mode==='follow'?s.devices.find(d=>d.id===camera.deviceId):null;
 const send=id=>{const target=stateRef.current.events.find(e=>e.id===id),requiredType=target?.status==='待复核'?'dog':'uav';const assigned=stateRef.current.devices.find(d=>d.id===pilot&&d.type===requiredType)?.id;const result=dispatch(stateRef.current,id,assigned);if(result.error)notify(result.error);else{set(result.state);setPilot('');setRun(true);notify('任务已接收，设备开始执行');}};
 const create=(x,z)=>{set(v=>addEvent(v,kind,x,z,severity));setPlacing(false);setRight(true);setTab('events');notify('灾情已布设，等待搜索发现或指定侦察');};
 const start=id=>{set(v=>startDevices(v,id));setRun(true);notify(id?'设备已启动':'全部设备已启动，机器狗等待复核任务');};
 const home=id=>{set(v=>returnDevices(v,id));setRun(true);notify('已下发归位指令，正在返回集结中心');};
  return <div className="shell">
  <main className="map-panel"><World devices={s.devices} events={visibleEvents} tasks={s.tasks} placing={placing} onCreate={create} onSelect={id=>{select(id);setRight(true);setTab('events');}} onDeviceSelect={follow} camera={camera} selected={selected} running={run} onFreeChange={setFreeHud} freeSpeed={flySpeed}/></main>
  <header><div className="brand"><span className="brand-icon">⌁</span><div>天穹 <b>SKYWARD</b><small>应急救援 · 空地协同仿真</small></div></div><div className="system"><i/> 本地仿真 <span>平台未连接</span></div><div className="command-actions"><div className="clock">T + {Math.floor(s.time/60).toString().padStart(2,'0')}:{Math.floor(s.time%60).toString().padStart(2,'0')}</div><select aria-label="仿真速度" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[1,4,10,30,120,300].map(v=><option key={v} value={v}>{v}×</option>)}</select><button onClick={()=>setRun(!run)}>{run?'Ⅱ 暂停仿真':'▶ 运行仿真'}</button></div></header>
  <div className="toolbar"><div className="toolbar-group"><button aria-pressed={left} onClick={()=>setLeft(!left)}>▤ 设备 <em>{s.devices.length}</em></button><button aria-pressed={right} onClick={()=>setRight(!right)}>◎ 灾情与任务 <em>{visibleEvents.length}</em></button><button aria-pressed={journal} onClick={()=>setJournal(!journal)}>≡ 记录</button></div><div className="toolbar-group"><button className="primary" onClick={()=>start()}>▶ 全部启动</button><button onClick={()=>home()}>↩ 全部归位</button></div></div>
  <div className="map-title"><small>QINGLAN / OPERATIONS FIELD</small><h1>青岚应急救援区域</h1><p>6.8 × 5.2 km · {active.length} 项任务执行中</p></div>
   {left&&<aside className="fleet panel"><div className="panel-heading"><div><small>CONNECTED FLEET</small><h2>设备集结中心</h2></div><button title="添加设备" aria-label="添加设备" onClick={()=>setModal('device')}>＋</button></div><input className="search" placeholder="搜索设备名称…" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="fleet-list">{s.devices.filter(d=>d.name.includes(filter)).map(d=>{const t=active.find(t=>t.deviceId===d.id);return <div className="device-card" key={d.id}><div className="device-title"><span className={'device-icon '+d.type}>{d.type==='uav'?'✣':'▰'}</span><div><b>{d.name}</b><small>{d.type==='uav'?'无人机 / AIR UNIT':'机器狗 / GROUND UNIT'}</small></div><i className={t||d.enabled?'working':''}/></div><div className="device-status"><span>{t?.stage==='前往目标'?t.phase:t?.stage||d.state||'待命'}</span><span>{d.battery.toFixed(0)}%</span></div><div className="battery"><i style={{width:d.battery+'%'}}/></div><div className="device-meta">停靠位 {String(d.berth+1).padStart(2,'0')} <span>{d.type==='uav'?`离地 ${Math.max(0,d.y-surfaceHeight(d.x,d.z)).toFixed(1)} m`:`作业距离 ${((d.maxDistance||DOG_MAX_DISTANCE)/1000).toFixed(1)} km`}</span></div><div className="row"><button onClick={()=>follow(d.id)}>◎ 跟随</button><button disabled={!!t||d.enabled} onClick={()=>start(d.id)}>启动</button><button onClick={()=>home(d.id)}>归位</button></div><div className="row secondary"><button disabled={!!t||d.enabled} onClick={()=>setModal({edit:d})}>配置</button><button className="danger-text" onClick={()=>setModal({remove:d})}>移除</button></div></div>;})}</div><div className="fleet-note">无人机搜索发现目标，机器狗抵近复核。<br/>新设备从中心停靠位上线。</div></aside>}
  {right&&<aside className="intel panel"><div className="tabs"><button className={tab==='events'?'chosen':''} onClick={()=>setTab('events')}>灾情 {visibleEvents.length}</button><button className={tab==='tasks'?'chosen':''} onClick={()=>setTab('tasks')}>任务 {s.tasks.length}</button><button aria-label="关闭灾情侧栏" onClick={()=>setRight(false)}>×</button></div><div className="intel-content">{tab==='events'?<>{!visibleEvents.length&&<div className="empty"><div className="empty-symbol">◎</div><h3>等待布设灾情</h3><p>在底部选择类型，点击地图布设，<br/>或随机生成一个可达目标。</p></div>}{visibleEvents.map(e=><button className={'event-card '+(selected===e.id?'selected':'')} key={e.id} onClick={()=>{select(e.id);setPilot('');focus(e.x,e.z);}}><div><span className={'severity '+(e.severity==='高'?'high':'')}>{e.severity}</span><b>{TYPES[e.kind]}</b></div><p>{region(e.x,e.z)} · {e.status}</p><small>{e.discoveredBy?`发现设备：${e.discoveredBy}`:'仿真注入 · 尚未上报'}<span>⌖ {e.x.toFixed(0)}, {e.z.toFixed(0)}</span></small></button>)}{event&&<div className="event-detail"><small>INCIDENT DETAIL</small><h3>{TYPES[event.kind]}</h3><div className="stages">{['待侦察','侦察中','待复核','复核中','处理中','已处理'].map(k=><span key={k} className={event.status===k?'current':''}>{k}</span>)}</div>{event.result&&<p className="result-card">✓ {event.result}<br/><small>当前标记将在数秒后自动收起，历史记录继续保留。</small></p>}{['待侦察','待复核'].includes(event.status)&&<><label className="assignment-label">执行设备<select aria-label="执行设备" value={pilot} onChange={e=>setPilot(e.target.value)}><option value="">自动选择可用设备</option>{s.devices.filter(d=>d.type===(event.status==='待侦察'?'uav':'dog')).map(d=><option key={d.id} value={d.id}>{d.name}{active.some(t=>t.deviceId===d.id)?'（忙碌）':''}</option>)}</select></label><button className="primary full" onClick={()=>send(event.id)}>{event.status==='待侦察'?'派遣无人机侦察':'派遣机器狗复核'} →</button></>}<button className="full danger-text" onClick={()=>setModal({removeEvent:event})}>删除事件</button></div>}</>:<>{!s.tasks.length&&<div className="empty">设备启动或派遣后，任务进度在这里显示。</div>}{s.tasks.map(t=><div className="task-card" key={t.id}><b>{t.phase} <span>{t.status}</span></b><p>{t.deviceName} · {t.stage}</p><progress value={t.progress} max="100"/><small>{Math.floor(t.progress)}% · 路径 {(t.totalDistance/1000).toFixed(2)} km</small>{t.status==='执行中'&&<button onClick={()=>mutate(n=>cancelTask(n,n.tasks.find(v=>v.id===t.id)))}>取消任务</button>}</div>)}</>}</div><div className="intel-footer"><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='skyward-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>↓ 导出记录</button><button className="danger-text" onClick={()=>setModal('reset')}>重置</button></div></aside>}
  <div className="view-buttons"><button onClick={()=>view('home')}>⌂ 中心</button><button onClick={()=>view('overview')}>◈ 全景</button><button onClick={()=>view('top')}>▦ 俯视</button><button className={freeHud?'flight-on':''} onClick={()=>view(freeHud?'exitfree':'free')}>{freeHud?'退出自由视角':'✥ 自由视角'}</button></div>
   {following&&!freeHud&&<div className="tracking"><div className="tracking-head"><span><i/> 正在跟随</span><b>{following.name}</b><button onClick={()=>view('orbit')}>退出跟随</button></div><div className="tracking-details"><div><small>TYPE</small><b>{following.type==='uav'?'无人机 / AIR UNIT':'机器狗 / GROUND UNIT'}</b></div><div><small>STATUS</small><b>{active.find(t=>t.deviceId===following.id)?.stage||following.state||'待命'}</b></div><div><small>仿真坐标 X / Z</small><b>{following.x.toFixed(0)} / {following.z.toFixed(0)} m</b></div><div><small>海拔 / 离地</small><b>{following.y.toFixed(1)} / {Math.max(0,following.y-surfaceHeight(following.x,following.z)).toFixed(1)} m</b></div><div><small>BATTERY</small><b className={following.battery<=20?'warning':''}>{following.battery.toFixed(0)}%</b></div>{following.type==='dog'&&<div><small>最大作业距离</small><b>{((following.maxDistance||DOG_MAX_DISTANCE)/1000).toFixed(1)} km</b></div>}</div></div>}
  {freeHud&&<div className="flight-hud"><span>WASD 移动 · Q/E 升降 · Shift 加速 · Esc 退出</span><label>速度<select aria-label="视角移动速度" value={flySpeed} onChange={e=>setFlySpeed(+e.target.value)}><option value="10">10 m/s</option><option value="30">30 m/s</option><option value="100">100 m/s</option></select></label></div>}
  {placing&&<div className="placement">⌖ 点击地图布设「{TYPES[kind]}」<button onClick={()=>setPlacing(false)}>取消</button></div>}
  <div className="scenario-bar"><div><small>SCENARIO</small><b>灾情布设</b></div><select aria-label="灾情类型" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="灾情等级" value={severity} onChange={e=>setSeverity(e.target.value)}>{['高','中','低'].map(k=><option key={k}>{k}</option>)}</select><button className={placing?'primary':''} onClick={()=>{setPlacing(!placing);setLeft(false);setRight(false);}}>⌖ {placing?'取消布设':'地图布设'}</button><button onClick={()=>{set(v=>randomEvent(v,kind,severity));setRight(true);setTab('events');notify('随机灾情已布设');}}>＋ 随机分布</button></div>
  {journal&&<section className="timeline panel"><div className="panel-heading"><h2>运行记录</h2><span>{saveError?'本地保存失败':'本地保存 · 协议事件 '+(s.messages?.length||0)}</span><button aria-label="关闭运行记录" onClick={()=>setJournal(false)}>×</button></div><div className="logs">{s.logs.map(l=><div key={l.id}><time>{l.time.toFixed(0)}s</time><i/>{l.text}</div>)}</div><p className="protocol-note">协议事件仅保存在本地，Kafka / HDFS / MongoDB / ES 尚未接入。</p></section>}
  <footer>仿真环境 / 程序生成地形<span>设备模型按米制显示 · {saveError?'保存失败':'本地存档'}</span></footer>
  {toast&&<div role="status" className="toast">{toast}</div>}
  {modal&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setModal(null)}>×</button>{modal==='device'||modal.edit?<DeviceForm device={modal.edit} onSubmit={fields=>{try{const n=structuredClone(stateRef.current);if(modal.edit){n.devices=n.devices.map(d=>d.id===fields.id?{...d,...fields}:d);}else{const d=createDevice(n,fields);n.devices.push(d);emit(n,'device.register',d.id,{name:d.name,deviceType:d.type,cruise:d.cruise,maxDistance:d.maxDistance,position:d.home});}log(n,`${fields.name} 设备配置已保存`);set(n);setModal(null);}catch(e){notify(e.message);}}}/>:<><small>CONFIRM ACTION</small><h2>{modal==='reset'?'重置整个仿真？':modal.remove?'移除这台设备？':'删除这条事件？'}</h2><p>{modal==='reset'?'设备恢复默认编组，清空当前灾情、任务与记录。':'关联执行任务将取消，保留任务历史。'}</p><div className="row"><button onClick={()=>setModal(null)}>保留</button><button className="danger" onClick={()=>{if(modal==='reset'){set(fresh());setRun(false);select(null);view('home');}else mutate(n=>{for(const t of n.tasks.filter(t=>t.status==='执行中'&&(modal.remove?t.deviceId===modal.remove.id:t.eventId===modal.removeEvent.id)))cancelTask(n,t);if(modal.remove){emit(n,'device.offline',modal.remove.id,{reason:'REMOVED'});n.devices=n.devices.filter(d=>d.id!==modal.remove.id);log(n,`${modal.remove.name} 已移除`);if(camera.deviceId===modal.remove.id)view('home');}else{n.events=n.events.filter(e=>e.id!==modal.removeEvent.id);log(n,'操作员删除事件');select(null);}});setModal(null);}}>确认</button></div></>}</div></div>}
 </div>;
}
function DeviceForm({device,onSubmit}){const [type,setType]=useState(device?.type||'uav');return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSubmit({...(device?{id:device.id}:{}),name:f.get('name').trim(),type,...(type==='uav'?{cruise:+f.get('height')}:{maxDistance:+f.get('maxDistance')})});}}><small>FLEET CONFIGURATION</small><h2>{device?'配置设备':'添加救援设备'}</h2><label>设备名称<input name="name" required pattern=".*\S.*" maxLength="24" defaultValue={device?.name||''} placeholder="例如：苍穹 03" autoFocus/></label><label>设备类型<select name="type" disabled={!!device} value={type} onChange={e=>setType(e.target.value)}>{device&&<option value={device.type}>{device.type==='uav'?'无人机':'机器狗'}</option>}{!device&&<><option value="uav">无人机 · 空中侦察</option><option value="dog">机器狗 · 地面复核</option></>}</select>{device&&<input type="hidden" name="type" value={device.type}/>}</label>{type==='uav'?<label key="uav">无人机巡航离地高度（m）<input name="height" type="number" min="60" max="150" step="10" defaultValue={device?.cruise||100} required/></label>:<label key="dog">机器狗最大作业距离（m）<input name="maxDistance" type="number" min="500" max="20000" step="100" defaultValue={device?.maxDistance||DOG_MAX_DISTANCE} required/></label>}<p>{type==='uav'?'设备从集结中心独立停靠位上线。':'超出该距离的地面复核任务不会派遣，距离按机器狗当前位置到目标的可通行路线计算。'}</p><button className="primary full" type="submit">保存设备</button></form>;}
 createRoot(document.getElementById('root')).render(<App/>);
